# []DataSource]
spring.datasource.url: 'jdbc:h2:mem:testdb'
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: ''

# [console do H2]
spring.h2.console.enabled: true # Ativa o console no via navegador
spring.h2.console.path: /h2-console # Definição do path (ex.: http://localhost:8080/h2-console)

# [Config JPA]
spring.jpa.show-sql: true

# Configuração de logs
logging.level.org.springframework: INFO
logging.level.com.exemplo.hexagonal: DEBUG

logging.pattern.console: '[%d{yyyy-MM-dd HH:mm:ss}] [%-5level] [%logger{0}] :: %msg%n'